# Generated by Django 4.2.7 on 2023-11-06 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('branch_number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('tel_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('registration_date', models.DateField()),
                ('branch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielib.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('catalog_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('video_number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('daily_rental', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('actors', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('branch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielib.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('rental_number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('rental_date', models.DateField()),
                ('return_date', models.DateField()),
                ('due_date', models.DateField()),
                ('branch_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielib.branch')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielib.member')),
                ('video_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movielib.video')),
            ],
        ),
    ]
